version: "2.1"

services:

  app:
    build: .
    volumes: ["app-data:/home"]
    ports: ["8001:8001"]
    networks: [backing-services]
    restart: unless-stopped
    mem_limit: 209715200 # container limit: 200Mb (200 * 1024 * 1024)

volumes:
  app-data: {}

networks:
  backing-services:
    driver: bridge
